IO.puts('esse é o Caddus que marcará 2023')
IO.puts('NeoCaddusX o Caddus feito na 4 linguagem de programação aprendida, ELIXIR')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')
IO.puts('apenas para preencher espaço, lol')

